/* Demo engagements across the venues and off-premise operations. */
import type { EventBooking } from "./types";

export const SEED_EVENTS: EventBooking[] = [
  {
    id: "FN-2041",
    name: "Werribee Park Wedding — Saturday",
    site: "Werribee Park Mansion",
    siteId: "s-werribee-wedding",
    client: "Private — Nguyen & Cole",
    status: "Active",
    start: "May 16, 2026",
    end: "May 17, 2026",
    filled: 18,
    required: 20,
    progress: 64,
    crew: ["Mia Anderson", "James Carter", "Sarah Bennett", "Alex Nguyen", "Priya Shah", "Tom Walker"],
    requirements: ["RSA", "Allergen Management", "Food Safety Supervisor", "Event site briefing"],
  },
  {
    id: "FN-2038",
    name: "Docklands Corporate Lunch Series",
    site: "Meridian Tower, Docklands",
    siteId: "s-docklands-lunch",
    client: "Meridian Group",
    status: "Active",
    start: "Apr 12, 2026",
    end: "Oct 12, 2026",
    filled: 11,
    required: 14,
    progress: 48,
    crew: ["Daniel Lee", "Grace Kim", "Olivia Brown", "Ethan Park"],
    requirements: ["RSA", "Food Handler Training", "Allergen Management", "Corporate presentation standards"],
  },
  {
    id: "FN-2035",
    name: "Brightwater Friday Live",
    site: "Brightwater Hotel, Fitzroy",
    siteId: "s-brightwater",
    client: "In-house",
    status: "Active",
    start: "Mar 03, 2026",
    end: "Aug 30, 2026",
    filled: 24,
    required: 24,
    progress: 81,
    crew: ["Noah White", "Liam Scott", "Ava Turner", "Lucas Hall", "Chloe Green", "Mason Reed"],
    requirements: ["RSA", "Late-night availability", "Crowd safety briefing"],
  },
  {
    id: "FN-2033",
    name: "Northside Long Lunch",
    site: "Northside Tavern, Brunswick",
    siteId: "s-northside",
    client: "In-house",
    status: "Active",
    start: "Feb 18, 2026",
    end: "Dec 18, 2026",
    filled: 30,
    required: 36,
    progress: 55,
    crew: ["Isabella Cruz", "Henry Ford", "Zoe Adams", "Jack Morris", "Ruby Hayes"],
    requirements: ["RSA", "Food Safety Supervisor", "Food Handler Training", "Venue induction"],
  },
  {
    id: "FN-2055",
    name: "Brightwater Gaming Floor — Winter Roster",
    site: "Brightwater Gaming Room, Fitzroy",
    siteId: "s-brightwater-gaming",
    client: "In-house",
    status: "Active",
    start: "May 20, 2026",
    end: "Nov 20, 2026",
    filled: 20,
    required: 30,
    progress: 42,
    crew: ["Eli Stone", "Naomi Frost", "Pablo Diaz", "Greta Lund", "Sam Okafor"],
    requirements: ["RSA", "RSG", "Venue induction", "Rotating roster availability"],
  },
  {
    id: "FN-2052",
    name: "Spring Carnival Marquee",
    site: "Flemington — Marquee C",
    client: "Halcyon Labs",
    status: "Scheduled",
    start: "Nov 03, 2026",
    end: "Nov 07, 2026",
    filled: 6,
    required: 40,
    progress: 12,
    crew: ["Leo Bennett", "Maya Singh", "Owen Clark"],
    requirements: ["RSA", "Allergen Management", "Marquee service experience", "Evening availability"],
  },
  {
    id: "FN-2050",
    name: "Summer Festival Bar Pool",
    site: "Alexandra Gardens, Melbourne",
    client: "City Events Co.",
    status: "Scheduled",
    start: "Dec 04, 2026",
    end: "Feb 04, 2027",
    filled: 9,
    required: 50,
    progress: 18,
    crew: ["Cody Banks", "Nina Patel", "Riley Cooper"],
    requirements: ["RSA", "Crowd control briefing", "Outdoor bar experience", "Shift-work availability"],
  },
  {
    id: "FN-2048",
    name: "School Presentation Night",
    site: "Brunswick Grammar Hall",
    client: "Brunswick Grammar",
    status: "Scheduled",
    start: "Sep 06, 2026",
    end: "Sep 07, 2026",
    filled: 4,
    required: 22,
    progress: 9,
    crew: ["Hannah Lowe", "Ben Foster"],
    requirements: ["Working with Children Check", "Food Handler Training", "Allergen Management"],
  },
  {
    id: "FN-2058",
    name: "Quayside Product Launch",
    site: "Quayside Bar & Kitchen, Docklands",
    siteId: "s-quayside",
    client: "Aperture Studios",
    status: "Scheduled",
    start: "Sep 13, 2026",
    end: "Sep 13, 2026",
    filled: 3,
    required: 18,
    progress: 8,
    crew: ["Owen Pratt", "Lara Webb"],
    requirements: ["RSA", "Canapé service", "Allergen Management", "Event site briefing"],
  },
  {
    id: "FN-2026",
    name: "Peninsula Conference Catering",
    site: "Peninsula Resort, Sorrento",
    client: "Peninsula Resorts",
    status: "On Hold",
    start: "Jan 15, 2026",
    end: "Apr 15, 2026",
    filled: 7,
    required: 16,
    progress: 35,
    crew: ["Ella Brooks", "Marco Rossi", "Sophie Dean"],
    requirements: ["Food Safety Supervisor", "Allergen Management", "Early-start availability"],
  },
  {
    id: "FN-2022",
    name: "Corporate Gala Dinner",
    site: "Royal Exhibition Building",
    client: "Ardent Partners",
    status: "On Hold",
    start: "Dec 01, 2025",
    end: "Jun 01, 2026",
    filled: 12,
    required: 18,
    progress: 58,
    crew: ["Aaron Cole", "Tara Mills", "Victor Ng", "Jade Reilly"],
    requirements: ["RSA", "Banquet experience", "Allergen Management", "Black-tie presentation"],
  },
  {
    id: "FN-2009",
    name: "Summer Function Pool",
    site: "Brightwater Hotel, Fitzroy",
    siteId: "s-brightwater",
    client: "In-house",
    status: "Completed",
    start: "Nov 01, 2025",
    end: "Feb 28, 2026",
    filled: 28,
    required: 28,
    progress: 100,
    crew: ["Ivy Chan", "Hugo Marsh", "Lily Quinn", "Felix Wood", "Amara Osei"],
    requirements: ["RSA", "Food Handler Training", "Banquet experience"],
  },
  {
    id: "FN-2004",
    name: "New Year's Eve Service",
    site: "Quayside Bar & Kitchen, Docklands",
    siteId: "s-quayside",
    client: "In-house",
    status: "Completed",
    start: "Dec 31, 2025",
    end: "Jan 01, 2026",
    filled: 15,
    required: 15,
    progress: 100,
    crew: ["Dylan Ross", "Mila Vega", "Caleb Ortiz", "Hana Ito"],
    requirements: ["RSA", "Late-night availability", "Crowd safety briefing"],
  },
  {
    id: "FN-1998",
    name: "Winter Wine Dinner Series",
    site: "Northside Tavern, Brunswick",
    siteId: "s-northside",
    client: "In-house",
    status: "Completed",
    start: "Jun 02, 2025",
    end: "Aug 25, 2025",
    filled: 32,
    required: 32,
    progress: 100,
    crew: ["Ryan Pace", "Kira Holt", "Devon Lyle", "Asha Roy"],
    requirements: ["RSA", "Wine service knowledge", "Allergen Management"],
  },
  /* --- week-scoped catering engagements, so a catering site has a week to
     show on /schedule. Dated inside May 12–18 2026, the week the schedule
     grid displays. --- */
  {
    id: "FN-2062",
    name: "Werribee Park Wedding — setup & styling",
    site: "Werribee Park Mansion",
    siteId: "s-werribee-wedding",
    client: "Private — Nguyen & Cole",
    status: "Scheduled",
    start: "May 15, 2026",
    end: "May 15, 2026",
    filled: 6,
    required: 6,
    progress: 100,
    crew: ["Sarah Bennett", "Tom Walker", "Alex Nguyen"],
    requirements: ["Event site briefing"],
  },
  {
    id: "FN-2063",
    name: "Docklands Corporate Lunch — Tuesday",
    site: "Meridian Tower, Docklands",
    siteId: "s-docklands-lunch",
    client: "Meridian Group",
    status: "Active",
    start: "May 12, 2026",
    end: "May 12, 2026",
    filled: 8,
    required: 8,
    progress: 100,
    crew: ["Priya Sharma", "Michael Tan", "Leanne Vidal"],
    requirements: ["RSA", "Allergen Management", "Food Safety Supervisor"],
  },
  {
    id: "FN-2064",
    name: "Docklands Corporate Lunch — Thursday",
    site: "Meridian Tower, Docklands",
    siteId: "s-docklands-lunch",
    client: "Meridian Group",
    status: "Active",
    start: "May 14, 2026",
    end: "May 14, 2026",
    filled: 5,
    required: 8,
    progress: 62,
    crew: ["Priya Sharma", "Michael Tan"],
    requirements: ["RSA", "Allergen Management", "Food Safety Supervisor"],
  },
];
